# Generated by Django 4.1.7 on 2023-04-02 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='prompt',
            name='type',
            field=models.CharField(max_length=16),
        ),
        migrations.AddField(
            model_name='quiz',
            name='movie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='movie_titles', to='quiz.movie'),
            preserve_default=False,
        ),
    ]
