# Generated by Django 4.1.7 on 2023-04-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_movie_alter_prompt_type_quiz_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='life',
            field=models.IntegerField(default=3),
        ),
    ]
